### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by NickLarsenNZ** [stackabletech/crddocs#44]
When you visit: https://crds.stackable.tech/24.7.0/zookeeper.stackable.tech/zookeepercluster/v1alpha1/

And click on the link highlighted below:
![Image](https://github.com/user-attachments/assets/c438af5b-2197-4024-9c9b-146855f6f731)

It takes us to: https://docs.stackable.tech/home/stable/concepts/roles-and-role-groups

Which is a 404 (and the version drop down in the top-right doesn't work).

![Image](https://github.com/user-attachments/assets/54cd9dcd-7b6c-4286-9882-99d592022926)

**Comment by lfrancke** [comment]
Hmm.... this is now at https://docs.stackable.tech/home/stable/concepts/stacklet.html
I don't think there's much we can do?

Other than doing a redirect from old to new?

**Comment by NickLarsenNZ** [comment]
Yeah, there should be redirects generated for pages that have moved.
I'll see if I can figure it out as we release the docs for 24.11.

**Comment by NickLarsenNZ** [comment]
@Techassi and I have taken a look, and cannot see why the redirect doesn't work.

https://github.com/stackabletech/documentation/blob/413528d16b43dd68ae73d2a6b2da5d026145dcf8/modules/concepts/pages/stacklet.adoc?plain=1#L2

**Comment by lfrancke** [comment]
I'll leave the decision up to you

**Comment by Techassi** [comment]
I chased this issue down a rabbit hole and finally figured out the issue. I will create a PR with the potential fix I have in mind and see if it helps.
