### ISSUE TITLE
CRD docs not generated for AirflowCluster 23.7.0 and up

### ISSUE THREAD

**Issue by fhennig** [stackabletech/crddocs#5]
There is an error in the conversion:

    spec.validation.openAPIV3Schema.properties[spec].properties[clusterConfig].default.credentialsSecret: Invalid value: "null": credentialsSecret in body must be of type string: "null"

The default value for the `credentialsSecret` is the empty string, and the field is required. It looks like at some point in the go code, the empty string is turned into a null value, and then the required field is missing.

@vsupalov and I investigated for a while, but couldn't find a quick and easy fix in the go code. Another fix could be to supply a different default value in our CRD definition, i.e. a string with a single space in it.

I also briefly tried to simply not do the conversion step at all, but could not get it to work after 30 minutes.

**Comment by fhennig** [comment]
update: The error only comes up in the validation step:

    errList := validation.ValidateCustomResourceDefinition(internal, v1.SchemeGroupVersion)

when the `return errors.New(errList.ToAggregate().Error())` ist removed, the CRD seems to actually look fine.

maybe this is the solution?

It just seems weird to remove the validation step here ...

**Comment by vsupalov** [comment]
Sidenote: The validation output of the application points to issues which *might* be good to know about. I have not found another linting solution which would provide feedback for CRDs.
